package com.taskinspect.responses;

import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.taskinspect.common.error.ApiException;
import com.taskinspect.requirements.Requirement;
import com.taskinspect.requirements.RequirementType;
import com.taskinspect.responses.dto.SaveResponseRequest;
import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;
import org.springframework.http.HttpStatus;
import org.springframework.test.util.ReflectionTestUtils;

/** Unit tests of which answer fits which requirement type (task 9.1a). */
class ResponseValidationTests {

    private static final SaveResponseRequest BOOLEAN = answer(true, null, null, null);
    private static final SaveResponseRequest TEXT = answer(null, "All clean", null, null);
    private static final SaveResponseRequest NUMBER = answer(null, null, new BigDecimal("4.5"), null);

    @ParameterizedTest
    @EnumSource(value = RequirementType.class, names = {"CHECKBOX", "YES_NO"})
    void yesNoTypesTakeOnlyABoolean(RequirementType type) {
        Requirement requirement = requirement(type);

        valid(requirement, BOOLEAN);
        valid(requirement, answer(false, null, null, null));
        invalid(requirement, answer(null, null, null, null));
        invalid(requirement, TEXT);
        invalid(requirement, answer(true, "and a text", null, null));
        invalid(requirement, answer(true, null, BigDecimal.ONE, null));
    }

    @ParameterizedTest
    @EnumSource(value = RequirementType.class, names = {"TEXT", "COMMENT"})
    void textTypesTakeOnlyText(RequirementType type) {
        Requirement requirement = requirement(type);

        valid(requirement, TEXT);
        invalid(requirement, answer(null, "   ", null, null));
        invalid(requirement, BOOLEAN);
        invalid(requirement, answer(false, "All clean", null, null));
    }

    @Test
    void numberTakesOnlyANumber() {
        Requirement requirement = requirement(RequirementType.NUMBER);

        valid(requirement, NUMBER);
        valid(requirement, answer(null, null, BigDecimal.ZERO, null));
        invalid(requirement, TEXT);
        invalid(requirement, answer(null, "4.5", new BigDecimal("4.5"), null));
    }

    @Test
    void aBlankTextBesideTheRightValueIsIgnored() {
        valid(requirement(RequirementType.NUMBER), answer(null, " ", BigDecimal.TEN, null));
    }

    @Test
    void dropdownTakesExactlyOneOfItsOptions() {
        Requirement requirement = requirement(RequirementType.DROPDOWN);
        UUID first = optionId(requirement, 0);
        UUID second = optionId(requirement, 1);

        valid(requirement, answer(null, null, null, List.of(second)));
        invalid(requirement, answer(null, null, null, List.of()));
        invalid(requirement, answer(null, null, null, List.of(first, second)));
        invalid(requirement, answer(null, null, null, List.of(UUID.randomUUID())));
        invalid(requirement, answer(true, null, null, List.of(first)));
    }

    @Test
    void multipleSelectionTakesDifferentOptionsOfItsOwn() {
        Requirement requirement = requirement(RequirementType.MULTIPLE_SELECTION);
        UUID first = optionId(requirement, 0);
        UUID second = optionId(requirement, 1);
        UUID otherRequirementsOption = optionId(requirement(RequirementType.MULTIPLE_SELECTION), 0);

        valid(requirement, answer(null, null, null, List.of(first)));
        valid(requirement, answer(null, null, null, List.of(first, second)));
        invalid(requirement, answer(null, null, null, null));
        invalid(requirement, answer(null, null, null, List.of(first, first)));
        invalid(requirement, answer(null, null, null, List.of(first, otherRequirementsOption)));
        invalid(requirement, answer(null, "and a text", null, List.of(first)));
    }

    @ParameterizedTest
    @EnumSource(value = RequirementType.class, names = {"PHOTO", "DOCUMENT"})
    void evidenceTypesAreAnsweredByUploading(RequirementType type) {
        assertThatThrownBy(() -> ResponseService.validate(requirement(type), TEXT))
                .isInstanceOf(ApiException.class)
                .extracting("status", "code")
                .containsExactly(HttpStatus.BAD_REQUEST, ResponseService.USE_EVIDENCE_UPLOAD);
    }

    private static Requirement requirement(RequirementType type) {
        Requirement requirement = new Requirement(null, "Check the pump", null, type, true, 0, null,
                List.of("Good", "Worn", "Broken"));
        // Option IDs are generated by the database; set them as if saved.
        requirement.getOptions().forEach(o -> ReflectionTestUtils.setField(o, "id", UUID.randomUUID()));
        return requirement;
    }

    private static UUID optionId(Requirement requirement, int index) {
        return requirement.getOptions().get(index).getId();
    }

    private static SaveResponseRequest answer(Boolean booleanValue, String text, BigDecimal number,
            List<UUID> selected) {
        return new SaveResponseRequest(booleanValue, text, number, selected, "a note");
    }

    private static void valid(Requirement requirement, SaveResponseRequest request) {
        assertThatCode(() -> ResponseService.validate(requirement, request)).doesNotThrowAnyException();
    }

    private static void invalid(Requirement requirement, SaveResponseRequest request) {
        assertThatThrownBy(() -> ResponseService.validate(requirement, request))
                .isInstanceOf(ApiException.class)
                .extracting("status", "code")
                .containsExactly(HttpStatus.BAD_REQUEST, ResponseService.INVALID_RESPONSE);
    }

}
