package com.taskinspect.filestorage;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.InvalidKeyException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.HexFormat;
import java.util.Map;
import java.util.OptionalLong;
import java.util.regex.Pattern;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.stereotype.Component;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

/**
 * Stores files in a local folder and signs URLs like S3 pre-signed URLs:
 * {@code /api/files/<key>?expires=...&maxBytes=...&signature=...}, served by
 * {@link LocalFileController} without a login. The signing key is random
 * per start, so URLs stop working after a restart (they are only valid
 * for minutes anyway). For development and tests; not for production
 * with several backend instances.
 */
@Component
@ConditionalOnProperty(name = "taskinspect.storage.type", havingValue = "local", matchIfMissing = true)
@EnableConfigurationProperties(LocalFileStorageProperties.class)
public class LocalFileStorage implements FileStorage {

    static final String PATH_PREFIX = "/api/files/";

    /** Keys are generated by the backend: {@code tasks/<uuid>/<uuid>.<ext>}. */
    private static final Pattern KEY = Pattern.compile(
            "tasks/[0-9a-f-]{36}/[0-9a-f-]{36}\\.(jpg|png|pdf)");

    private static final SecureRandom RANDOM = new SecureRandom();

    private final Path root;
    private final byte[] signingKey = new byte[32];
    private final Clock clock;

    public LocalFileStorage(LocalFileStorageProperties properties, Clock clock) {
        this.root = properties.directory().toAbsolutePath().normalize();
        this.clock = clock;
        RANDOM.nextBytes(signingKey);
    }

    @Override
    public SignedUrl uploadUrl(String key, String contentType, long maxBytes, Duration validFor) {
        Instant expires = expiry(validFor);
        String signature = sign("PUT", key, contentType, maxBytes, expires.getEpochSecond());
        String url = baseUrl() + key + "?expires=" + expires.getEpochSecond() + "&maxBytes=" + maxBytes
                + "&signature=" + signature;
        return new SignedUrl(url, "PUT", Map.of("Content-Type", contentType), expires);
    }

    @Override
    public SignedUrl downloadUrl(String key, Duration validFor) {
        Instant expires = expiry(validFor);
        String signature = sign("GET", key, "", 0, expires.getEpochSecond());
        String url = baseUrl() + key + "?expires=" + expires.getEpochSecond() + "&signature=" + signature;
        return new SignedUrl(url, "GET", Map.of(), expires);
    }

    @Override
    public OptionalLong size(String key) {
        Path file = resolve(key);
        try {
            return Files.isRegularFile(file) ? OptionalLong.of(Files.size(file)) : OptionalLong.empty();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    @Override
    public void delete(String key) {
        try {
            Files.deleteIfExists(resolve(key));
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /** Checks a signed URL; false if the signature is wrong or the URL has expired. */
    boolean verify(String method, String key, String contentType, long maxBytes, long expires, String signature) {
        if (!isValidKey(key) || signature == null || clock.instant().getEpochSecond() > expires) {
            return false;
        }
        String expected = sign(method, key, contentType == null ? "" : contentType, maxBytes, expires);
        return MessageDigest.isEqual(expected.getBytes(StandardCharsets.US_ASCII),
                signature.getBytes(StandardCharsets.US_ASCII));
    }

    /**
     * Stores the uploaded bytes. Returns false (and stores nothing) if there
     * are more than {@code maxBytes}. The file appears only when complete.
     */
    boolean write(String key, InputStream content, long maxBytes) throws IOException {
        Path target = resolve(key);
        Path directory = target.getParent();
        if (directory == null) {
            throw new IllegalArgumentException("Invalid storage key");
        }
        Files.createDirectories(directory);
        Path temp = Files.createTempFile(directory, ".upload-", ".tmp");
        try {
            long total = 0;
            byte[] buffer = new byte[64 * 1024];
            try (OutputStream out = Files.newOutputStream(temp)) {
                int read;
                while ((read = content.read(buffer)) != -1) {
                    total += read;
                    if (total > maxBytes) {
                        return false;
                    }
                    out.write(buffer, 0, read);
                }
            }
            Files.move(temp, target, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
            return true;
        } finally {
            Files.deleteIfExists(temp);
        }
    }

    /** The stored file, or null if it does not exist. */
    Path file(String key) {
        Path file = resolve(key);
        return Files.isRegularFile(file) ? file : null;
    }

    static boolean isValidKey(String key) {
        return key != null && KEY.matcher(key).matches();
    }

    private Path resolve(String key) {
        if (!isValidKey(key)) {
            throw new IllegalArgumentException("Invalid storage key");
        }
        Path file = root.resolve(key).normalize();
        if (!file.startsWith(root)) {
            throw new IllegalArgumentException("Invalid storage key");
        }
        return file;
    }

    private Instant expiry(Duration validFor) {
        return clock.instant().plus(validFor).truncatedTo(ChronoUnit.SECONDS);
    }

    /** HMAC-SHA256 over the request details (package-private for tests). */
    String sign(String method, String key, String contentType, long maxBytes, long expires) {
        String data = String.join("\n", method, key, contentType, Long.toString(maxBytes), Long.toString(expires));
        try {
            Mac mac = Mac.getInstance("HmacSHA256");
            mac.init(new SecretKeySpec(signingKey, "HmacSHA256"));
            return HexFormat.of().formatHex(mac.doFinal(data.getBytes(StandardCharsets.UTF_8)));
        } catch (NoSuchAlgorithmException | InvalidKeyException e) {
            throw new IllegalStateException(e);
        }
    }

    /** Absolute URL of the file endpoint, as seen by the client of the current request. */
    private static String baseUrl() {
        return ServletUriComponentsBuilder.fromCurrentContextPath().path(PATH_PREFIX).build().toUriString();
    }

}
