spring:
  application:
    name: taskinspect-backend

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
